name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v3

    - name: Build Docker image
        run: docker build -f .github/workflows/temperature-converter/Dockerfile -t my-app .

    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Push Docker image to Heroku
      run: |
        docker tag calc-cli registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Heroku app
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
